braj15-sp2
nvbach91/4IZ268-2022-2023-ZS pull request #104
Opened 2022-12-23 11:12 UTC by brazdahonza

zatim kostra kodu, budu dal upravovat

2023-01-13 15:28 UTC, nvbach91 commented
Poznamky k SP1 k nalezeni v homepage HTML souboru zde:
https://github.com/nvbach91/4IZ268-2022-2023-ZS/tree/main/www/sp1,

aktualni stav bodu zde:
https://dev.itake.cz/link/

Nezapomente sem dat odkaz na aplikaci

2023-01-26 10:59 UTC, nvbach91 commented
@brazdahonza prosim odkaz na aplikaci

2023-01-26 11:02 UTC, brazdahonza commented
@nvbach91 
https://esotemp.vse.cz/~braj15/sp2/

2023-01-26 14:56 UTC, nvbach91 requested changes
![image](https://user-images.githubusercontent.com/20724910/214866971-0c2b2a0c-ec7c-4def-88fc-9e1bebab37c8.png)

- bude potreba novy pull request protoze soubory nahravate do nespravne slozky

2023-01-26 14:56 UTC, nvbach91 commented on www/js/app.js
> +                            //TO-DO ukladani do local storage fav receptu
chybi ukladani do localstorage

2023-01-26 14:56 UTC, nvbach91 commented on www/js/app.js
> +                $("#spinner-container").addClass("hidden");
elementy vybirame pouze jednou

2023-01-26 14:56 UTC, nvbach91 commented on www/js/app.js
> +                apiKey: "1961be2e72ea481d8dbfc63298ff0ecb"
apiKey dejte do promenne

2023-01-26 14:56 UTC, nvbach91 commented on www/js/app.js
> +            if (inputElement.val() === "") {
nedostatecne osetreni vstupu

2023-01-26 14:56 UTC, nvbach91 commented on www/js/app.js
> +        listElement.click(() => {
udelal bych na to mazani vyhrazene tlacitko u kazde ingredience

2023-01-26 14:56 UTC, nvbach91 commented on www/js/app.js
> +                let foodImage = $(`<img src=${recipes[i].image}></img>`);
`"`

2023-01-26 14:56 UTC, nvbach91 commented on www/js/app.js
> +                let foodImage = $(`<img src=${recipes[i].image}></img>`);
img je neparovy tag + chybi alt

2023-01-26 14:56 UTC, nvbach91 commented on www/js/app.js
> +            localStorage.clear();
tady schvalne mazete localStorage?

2023-01-26 14:56 UTC, nvbach91 commented on www/js/app.js
> +            meal.attr('class', `meal-item-${i}`);
k cemu je trida `meal-item-*`?

2023-01-26 14:56 UTC, nvbach91 commented on www/js/app.js
> +                if (ingredience == listElement.text()) {
mazani z pole se dela lepe pomoci filter

2023-01-26 14:56 UTC, nvbach91 commented on www/js/app.js
> +            listElement.remove();
po vymazu ingredience je potreba take aktualizovat localstorage

2023-01-27 14:57 UTC, closed without merging