Initial commit of SP2
nvbach91/4IZ268-2022-2023-ZS pull request #106
Opened 2022-12-23 12:28 UTC by Nikinayzer

In-prod version. Další úpravy cooming soon!

2023-01-05 22:40 UTC, nvbach91 commented
Poznamky k SP1 k nalezeni v homepage HTML souboru zde: 
- https://github.com/nvbach91/4IZ268-2022-2023-ZS/tree/main/www/sp1, 

aktualni stav bodu zde: 
- https://dev.itake.cz/link/

SP1 lze opravovat az do obhajoby.

2023-01-12 22:22 UTC, nvbach91 requested changes
vypada to, ze aplikace neni v pripravenem stavu

2023-01-13 02:07 UTC, Nikinayzer commented
Dobry den, nahral jsem updated vesrion
Odkaz: https://nikinayzer.github.io/Bar-Scout/

2023-01-13 10:51 UTC, nvbach91 approved these changes

2023-01-13 10:51 UTC, merged