lean04-sp2
nvbach91/4IZ268-2022-2023-ZS pull request #107
Opened 2022-12-23 12:43 UTC by leanhvie

https://github.com/nvbach91/4IZ268-2022-2023-ZS/commit/9483e73d9a561c0fb4e1b3ed83060175f29ac474: Boilerplate kód pro React a Typescript vytvořený přes `create-react-app` + další konfigurační soubory pro Typescript, eslint a prettier.

2023-01-13 18:33 UTC, nvbach91 commented
Nezapomen sem potom dat odkaz na aplikaci

Poznamky k SP1 k nalezeni v homepage HTML souboru zde:
https://github.com/nvbach91/4IZ268-2022-2023-ZS/tree/main/www/sp1,

aktualni stav bodu zde:
https://dev.itake.cz/link/

2023-02-01 14:16 UTC, leanhvie commented
Nemohl jsem pouzivat https://api.igdb.com/v4 kvuli komplikace s CORS a wrapper na API wrapper pro https://howlongtobeat.com neni mozny pouzit z browseru, protoze interne nastavuje headery, ktery browser zakazuje manualne nastavit. Nakonec jsem pouzil API z https://api.rawg.io/docs/.

2023-02-02 21:52 UTC, nvbach91 requested changes

2023-02-02 21:52 UTC, nvbach91 commented on www/lean04/sp2/src/api/rawg.ts
> +const apiKey = 'b705c5897b954f31954253bedbeaa46b';
dotenv?

2023-02-02 21:52 UTC, nvbach91 commented on www/lean04/sp2/src/App/ContextProviders.tsx
> +        window.localStorage.setItem('dataSource', JSON.stringify(dataSource));
lepsi nazev klice

2023-02-02 21:52 UTC, nvbach91 commented on www/lean04/sp2/src/components/AddGameModal/GameDescription.tsx
> +        {released ? <Descriptions.Item label="Released on">{released}</Descriptions.Item> : null}
nejaky obrazek by nebylo mozne zobrazit?

2023-02-03 14:39 UTC, nvbach91 approved these changes

2023-02-03 14:39 UTC, merged