kulm11-sp2
nvbach91/4IZ268-2022-2023-ZS pull request #109
Opened 2022-12-23 13:28 UTC by MichK28

https://esotemp.vse.cz/~kulm11/sp2/
Pilotní verze aplikace. Aplikace propojena s API. Lze vytvářet seznam filmů.

2023-01-13 16:28 UTC, nvbach91 commented
Poznamky k SP1 k nalezeni v homepage HTML souboru zde:
https://github.com/nvbach91/4IZ268-2022-2023-ZS/tree/main/www/sp1,

aktualni stav bodu zde:
https://dev.itake.cz/link/

2023-01-25 18:55 UTC, MichK28 commented
poslední comimit je finální verzí k obhajobě

2023-01-26 12:45 UTC, nvbach91 requested changes
vyhledavani by melo fungovat takto: zobrazi se seznam filmu, ktere odpovidaji zadanemu klicovemu slovu, a uzivatel si z toho seznamu vybere co chce sledovat.

2023-01-26 12:45 UTC, nvbach91 commented on www/kulm11/sp2/assets/js/main.js
> +        const movieUrl = `https://www.omdbapi.com/?t=${movieTitleUpdated}&apikey=4c7468f7`;
tady ma byt `?s=...`

2023-01-26 12:45 UTC, nvbach91 commented on www/kulm11/sp2/assets/js/main.js
> +        const movieTitleUpdated = movieTitle.replace(' ', '+').replace(':', '%3A');
tohle se dela pomoci `encodeURIComponent()`

2023-01-26 12:45 UTC, nvbach91 commented on www/kulm11/sp2/assets/js/main.js
> +                    movieElement.appendChild(movieInfo);
`movieElement.append(movieImageElement, movieName, ...)`

2023-01-26 12:45 UTC, nvbach91 commented on www/kulm11/sp2/assets/js/main.js
> +    filterUserRatingValue.setAttribute("max", 100);
tyhle atributy vam budou fungovat jenom kdyz se jejich formular (ktery asi neni) pokousi o submitnuti

2023-01-26 12:45 UTC, nvbach91 commented on www/kulm11/sp2/assets/js/main.js
> +        movieRemoveButton.remove();
jak smazu ze seznamu watched?

2023-01-26 12:45 UTC, nvbach91 commented on www/kulm11/sp2/assets/js/main.js
> +        movieElement.setAttribute("class", "movie");
`classList.add()`

2023-01-27 15:00 UTC, nvbach91 approved these changes

2023-01-27 15:00 UTC, merged