laum02 sp2
nvbach91/4IZ268-2022-2023-ZS pull request #115
Opened 2022-12-23 17:47 UTC by MichalLauer

https://esotemp.vse.cz/~laum02/sp2/

2023-01-05 18:53 UTC, nvbach91 requested changes
Poznamky:
- formular neni dostatecne osetreny proti nevalidnim zadavanim, napr. prazdny input
- zkuste pridat moznost pro "follow" nalezeneho uzivatele, tj. uzivatele ulozite do localstorage pro rychly pristup k nim behem pouzivani
- pridejte moznost ukladani vybranych tweetu do stazeneho JSON souboru (id tweetu, autor tweetu, datum a text)

2023-01-05 22:32 UTC, MichalLauer commented
Pro ověření vstupu je použit robustnější regex. Vstup se validuje jak v HTML, tak v JS.
Přidáno tlačítko na sledování uživatele, který se přidá do selectu vedle vyhledávání.
Přidán link na stáhnutí posledního tweetu ve formátu JSON.

2023-01-05 22:37 UTC, nvbach91 commented
Poznamky k SP1 k nalezeni v homepage HTML souboru zde: 
- https://github.com/nvbach91/4IZ268-2022-2023-ZS/tree/main/www/sp1, 

aktualni stav bodu zde: 
- https://dev.itake.cz/link/

2023-01-06 09:36 UTC, nvbach91 approved these changes

2023-01-06 09:36 UTC, merged