vanp04-sp2
nvbach91/4IZ268-2022-2023-ZS pull request #116
Opened 2022-12-23 19:37 UTC by Asuzuri

https://esotemp.vse.cz/~vanp04/sp2/

2023-01-13 17:22 UTC, nvbach91 commented
Poznamky k SP1 k nalezeni v homepage HTML souboru zde:
https://github.com/nvbach91/4IZ268-2022-2023-ZS/tree/main/www/sp1,

aktualni stav bodu zde:
https://dev.itake.cz/link/

2023-01-25 16:34 UTC, Asuzuri commented
https://esotemp.vse.cz/~vanp04/sp2/. Finální verze odevzdána.

2023-01-26 14:19 UTC, nvbach91 requested changes

2023-01-26 14:19 UTC, nvbach91 commented on www/vanp04/sp2/assets/js/main.js
> +    const createCurrentWeatherContentItem = (WeatherCurrent, countryCode, cityName) => {
`weatherCurrent`

2023-01-26 14:19 UTC, nvbach91 commented on www/vanp04/sp2/assets/js/main.js
> +    const createHourlyWeatherItem = (WeatherHourly, hour) => {
`weatherHourly`

2023-01-26 14:19 UTC, nvbach91 commented on www/vanp04/sp2/assets/js/main.js
> +            this.humidity = humidity,
strednik?

2023-01-26 14:19 UTC, nvbach91 commented on www/vanp04/sp2/assets/js/main.js
> +            sortByAnime = 'score';
neslo by tyhle udalosti parametrizovat?

2023-01-26 14:19 UTC, nvbach91 commented on www/vanp04/sp2/assets/js/main.js
> +        getWeather(lat, lon);
pridat button -> nabidnout moznost znovunacteni geolokace v pripade odmitnuti

2023-01-27 15:22 UTC, nvbach91 approved these changes

2023-01-27 15:22 UTC, merged