lasj06 - sp2
nvbach91/4IZ268-2022-2023-ZS pull request #117
Opened 2022-12-23 19:59 UTC by Gladyon

Adding a basic structure for sp2

2023-01-13 18:26 UTC, nvbach91 commented
Nezapomente sem dat odkaz na aplikaci

Poznamky k SP1 k nalezeni v homepage HTML souboru zde:
https://github.com/nvbach91/4IZ268-2022-2023-ZS/tree/main/www/sp1,

aktualni stav bodu zde:
https://dev.itake.cz/link/

2023-01-14 12:26 UTC, Gladyon commented
https://esotemp.vse.cz/~lasj06/sp2/

2023-01-14 12:27 UTC, Gladyon commented
Chtěl bych se zeptat, dotazy ohledně připomínek k sp1 mám psát sem, nebo do sp1 pull request?

2023-01-14 12:35 UTC, nvbach91 commented
Staci provest upravy a ukazat je pri obhajobe

2023-01-14 13:05 UTC, Gladyon commented
Já se ptám proto, že v připomínkách jsou věci (např. přizpůsobení pro tisk), které práce již obsahuje a já nevím jak moc více na nich mám pracovat

2023-01-14 13:24 UTC, nvbach91 commented
U tisku se podivejte na prednasku z 7.10. a na pozadavky zakonceni https://4iz268.github.io/zakonceni/stranky/, a dale zde https://github.com/nvbach91/4IZ268-2022-2023-ZS/wiki/LAB05

2023-01-14 16:08 UTC, Gladyon commented
Děkuji

2023-02-02 23:03 UTC, nvbach91 requested changes
- nerozumim smysl aplikace
- v aplikaci chybi prace s browser api

2023-02-02 23:03 UTC, nvbach91 commented on www/sp2/index.html
> +    <div class="input-box" id="input-box">
`<form>`?

2023-02-02 23:03 UTC, nvbach91 commented on www/sp2/js/main.js
> +        const guessValue = document.getElementById('input').value;
elementy vybirame pouze jednou

2023-02-02 23:03 UTC, nvbach91 commented on www/sp2/js/main.js
> +    const randomnumber = (Math.random() * (1008 - 1 + 1)) << 0;
0 neni validni ID

2023-02-03 14:38 UTC, nvbach91 approved these changes

2023-02-03 14:38 UTC, closed without merging