proe11-sp2
nvbach91/4IZ268-2022-2023-ZS pull request #121
Opened 2022-12-23 21:54 UTC by DoubleOTism

Link na rozpracovanou SP2 - https://esotemp.vse.cz/~proe11/sp2

2023-01-13 16:54 UTC, nvbach91 commented
Poznamky k SP1 k nalezeni v homepage HTML souboru zde:
https://github.com/nvbach91/4IZ268-2022-2023-ZS/tree/main/www/sp1,

aktualni stav bodu zde:
https://dev.itake.cz/link/

2023-01-26 13:15 UTC, nvbach91 requested changes

2023-01-26 13:15 UTC, nvbach91 commented on www/proe11/sp2/js/main.js
> +      gameElement.append(`<img src="${gameImage}" alt="${gameSlug}" style="width:300px;height:170px;">`);
`width="300" height="170"` ? nebo jeste lepe `class="game-img"`?

2023-01-26 13:15 UTC, nvbach91 commented on www/proe11/sp2/js/main.js
> +  $('#search-field, #page-size-select, #platform-select, #genre-select').on('input', function () {
tady je potreba pridat tzv. `debounce`

2023-01-26 13:15 UTC, nvbach91 commented on www/proe11/sp2/js/main.js
> +      gameElement.append(`<img src="${gameImage}" alt="${gameSlug}" style="width:300px;height:170px;">`);
zase inline css

2023-01-26 13:15 UTC, nvbach91 commented on www/proe11/sp2/js/main.js
> +    $("#more-info-dialog").html(`<p>Videohra ${gameName} je již na seznamu.</p>`);
formatovani kodu

2023-01-26 13:15 UTC, nvbach91 commented on www/proe11/sp2/js/main.js
> +    var gameIndex = userGames.findIndex(game => game.name === gameName);
zkuste smazat 2. ze 3 ulozenych her a dat refresh

2023-01-26 13:15 UTC, nvbach91 commented on www/proe11/sp2/css/style.css
> +    width: 1920px;
udelat responzivni layout by nebylo spatne

2023-01-26 13:15 UTC, nvbach91 commented on www/proe11/sp2/js/main.js
> +    axios.get(`https://api.rawg.io/api/games/${slug}?key=860c2dc5a48346e69bf64f72d4ffb18b`)
chtelo by to nevolat na API pokud uz byl jednou volana stejna hra

2023-01-26 20:19 UTC, DoubleOTism commented on www/proe11/sp2/css/style.css
> +    width: 1920px;
Pokus o responzivní layout proběhl ve verzi 0.4.1 (špatně označeno jako 4.1)

2023-01-26 20:19 UTC, DoubleOTism commented on www/proe11/sp2/js/main.js
> +    var gameIndex = userGames.findIndex(game => game.name === gameName);
Oprava proběhla ve verzi 0.4

2023-01-26 20:19 UTC, DoubleOTism commented on www/proe11/sp2/js/main.js
> +    $("#more-info-dialog").html(`<p>Videohra ${gameName} je již na seznamu.</p>`);
Oprava (snad) proběhla ve verzi 0.4

2023-01-26 20:19 UTC, DoubleOTism commented on www/proe11/sp2/js/main.js
> +      gameElement.append(`<img src="${gameImage}" alt="${gameSlug}" style="width:300px;height:170px;">`);
Oprava proběhla ve verzi 0.4

2023-01-26 20:20 UTC, DoubleOTism commented on www/proe11/sp2/js/main.js
> +  $('#search-field, #page-size-select, #platform-select, #genre-select').on('input', function () {
debounce přidáno ve verzi 0.4

2023-01-26 20:20 UTC, DoubleOTism commented on www/proe11/sp2/js/main.js
> +      gameElement.append(`<img src="${gameImage}" alt="${gameSlug}" style="width:300px;height:170px;">`);
Odstraněno ve verzi 0.4

2023-01-26 20:20 UTC, DoubleOTism commented on www/proe11/sp2/js/main.js
> +    axios.get(`https://api.rawg.io/api/games/${slug}?key=860c2dc5a48346e69bf64f72d4ffb18b`)
Nejsem si jist tím, že dokážu provést opravu, jedná se o značnou chybu v případě, že to takto zůstane?

2023-01-27 15:01 UTC, nvbach91 approved these changes

2023-01-27 15:01 UTC, merged