marp30-sp2
nvbach91/4IZ268-2022-2023-ZS pull request #124
Opened 2022-12-23 22:06 UTC by marp307

Link to application https://esotemp.vse.cz/~marp30/sp2/

2023-01-17 13:13 UTC, nvbach91 commented
Poznamky k SP1 k nalezeni v homepage HTML souboru zde:
https://github.com/nvbach91/4IZ268-2022-2023-ZS/tree/main/www/sp1,

aktualni stav bodu zde:
https://dev.itake.cz/link/

2023-01-31 17:44 UTC, marp307 reviewed
Final version

2023-02-02 21:21 UTC, nvbach91 requested changes
- pridejte funkcionalitu aby uzivatele mohli ukladat mesta a po zvoleni ulozeneho mesta se provede nacteni dat o pocasi
- pouzijte browser api geolocation a zjistete nazev mesta ve kterem se uzivatel prave nachazi

2023-02-02 21:21 UTC, nvbach91 commented on www/marp30/sp2/index.html
> +                    <button class="primary" onclick="fetchByType()">Fetch</button>
nesmime pouzivat inline javascript.

2023-02-02 21:21 UTC, nvbach91 commented on www/marp30/sp2/main.js
> +const API_KEY = '2375c9005ed140a7b84edaa8fe79844a'
chybi closure

2023-02-02 21:21 UTC, nvbach91 commented on www/marp30/sp2/index.html
> +                    <input type="text" value="prague" name="city" id="cityInput">
chybi `<form>`

2023-02-02 21:21 UTC, nvbach91 commented on www/marp30/sp2/main.js
> +	$("#graph").html("");
elementy vybirame pouze jednou

2023-02-03 14:40 UTC, nvbach91 approved these changes

2023-02-03 14:40 UTC, merged