pesd05-sp2
nvbach91/4IZ268-2022-2023-ZS pull request #131
Opened 2022-12-24 00:40 UTC by pesd05

link: https://esotemp.vse.cz/~pesd05/sp2/

2023-01-06 17:09 UTC, nvbach91 commented
Poznamky k SP1 k nalezeni v homepage HTML souboru zde:
https://github.com/nvbach91/4IZ268-2022-2023-ZS/tree/main/www/sp1,

aktualni stav bodu zde:
https://dev.itake.cz/link/

2023-01-19 12:00 UTC, pesd05 commented
Finalni verze:
https://esotemp.vse.cz/~pesd05/sp02/ 
https://esotemp.vse.cz/~pesd05/sp02/levels/  
https://esotemp.vse.cz/~pesd05/sp02/levels/level1/  
https://esotemp.vse.cz/~pesd05/sp02/levels/level2/ 
https://esotemp.vse.cz/~pesd05/sp02/levels/level3/  
https://esotemp.vse.cz/~pesd05/sp02/end/

2023-01-19 13:44 UTC, nvbach91 requested changes
- aplikace ma byt single-page, tzn. ze bude pouze jeden index.html soubor, a veskere akce v ramci aplikace by nemely uzivatele presmerovavat na jinou stranku
- kod sp2 byl nahran do nespravne slozky
- nedostatecne vyuziti browser API

2023-01-19 13:44 UTC, nvbach91 commented on sp02/assets/js/easy.js
> +let questions = [];
kod bez closure

2023-01-19 13:44 UTC, nvbach91 commented on sp02/assets/js/game.js
> +startGame = () => {
chybi delarace promenne

2023-01-19 13:44 UTC, nvbach91 commented on sp02/assets/js/hard.js
> +    'https://opentdb.com/api.php?amount=20&category=10&difficulty=hard&type=multiple'
uroven hry musi byt v promenne, nesmime opakovat kod

2023-01-27 14:33 UTC, pesd05 commented
link: https://esotemp.vse.cz/~pesd05/sp02_nova/game/

2023-01-27 15:18 UTC, nvbach91 approved these changes

2023-01-27 15:18 UTC, merged