podj06-sp2
nvbach91/4IZ268-2022-2023-ZS pull request #132
Opened 2022-12-24 01:28 UTC by sprintfenjoyer

2023-01-17 13:23 UTC, nvbach91 commented
Nezapomente sem dat odkaz na aplikaci

Poznamky k SP1 k nalezeni v homepage HTML souboru zde:
https://github.com/nvbach91/4IZ268-2022-2023-ZS/tree/main/www/sp1,

aktualni stav bodu zde:
https://dev.itake.cz/link/

2023-02-02 03:52 UTC, sprintfenjoyer commented
Odkaz na aplikaci přidán

2023-02-02 22:40 UTC, nvbach91 requested changes
pridejte moznost ukladani zastavek do localstorage a rychle zobrazovani timetable techto ulozenych zastavek

2023-02-02 22:40 UTC, nvbach91 commented on www/podj06/sp2/frontend/index.html
> +    import {App} from "/assets/js/app.js";
tohle dejte do main.js

2023-02-02 22:40 UTC, nvbach91 commented on www/podj06/sp2/frontend/assets/js/jquery-3.6.3.min.js
> +/*! jQuery v3.6.3 | (c) OpenJS Foundation and other contributors | jquery.org/license */
pouzivejte CDN

2023-02-02 22:40 UTC, nvbach91 commented on www/podj06/sp2/frontend/assets/js/pages/stopPage.js
> +<div class="card-body row">
formatovani kodu

2023-02-02 22:40 UTC, nvbach91 commented on www/podj06/sp2/frontend/assets/js/pages/stopPage.js
> +
jak se dostanu zpatky na searchpage?

2023-02-02 22:40 UTC, nvbach91 commented on www/podj06/sp2/frontend/assets/js/pages/searchPage.js
> +const STOP_ELEMENT = `<a class="text-decoration-none" href="/stop?cisId=#cisId#"><div class="card mb-2">
aplikace musi byt single-page

2023-02-03 14:41 UTC, nvbach91 approved these changes

2023-02-03 14:41 UTC, merged