macz02-sp2
nvbach91/4IZ268-2022-2023-ZS pull request #148
Opened 2022-12-29 12:19 UTC by zmac11

https://esotemp.vse.cz/~macz02/sp2/

2022-12-29 12:28 UTC, zmac11 commented
Omlouvám se, ale pracoval jsem s původní informací, tj. odevzdání do konce roku. O změně termínu jsem nevěděl..

2023-01-01 21:38 UTC, nvbach91 commented
Puvodne byl termin do konce 13. tydne vyuky

2023-01-17 13:02 UTC, nvbach91 commented
Poznamky k SP1 k nalezeni v homepage HTML souboru zde:
https://github.com/nvbach91/4IZ268-2022-2023-ZS/tree/main/www/sp1,

aktualni stav bodu zde:
https://dev.itake.cz/link/

2023-02-02 22:26 UTC, nvbach91 requested changes
- pridejte funkcionalitu ukladani high score do localstorage

2023-02-02 22:26 UTC, nvbach91 commented on www/macz02/sp2/script.js
> +    const fetchUrl = eval(url);
co tady dela `eval()`?

2023-02-02 22:26 UTC, nvbach91 commented on www/macz02/sp2/index.html
> +    <img id="cat1" >
alt, src, generovat v js?

2023-02-02 22:26 UTC, nvbach91 commented on www/macz02/sp2/script.js
> +    game.startGame();
formatovani kodu

2023-02-02 22:26 UTC, nvbach91 commented on www/macz02/sp2/script.js
> +        const deltaTime = timeStamp - lastTime;
jak muzu hru pozastavit?

2023-02-02 22:26 UTC, nvbach91 commented on www/macz02/sp2/script.js
> +            this.winningScore = 222;
slo by tyhle nastaveni nakonfigurovat?

2023-02-03 14:40 UTC, nvbach91 approved these changes

2023-02-03 14:40 UTC, merged