wald03-hw08
nvbach91/4IZ268-2022-2023-ZS pull request #24
Opened 2022-11-12 12:25 UTC by wallerdav

Odevzdávám domácí úkol č.8
https://esotemp.vse.cz/~wald03/cv08/hw/

2022-11-14 14:41 UTC, nvbach91 commented on www/wald03/hw08/main.js
> +const age = 20;
ma to by rok narozeni

2022-11-14 14:41 UTC, nvbach91 commented on www/wald03/hw08/main.js
> +const first_celsius = 20;
pouzivame camelcase

2022-11-14 14:41 UTC, nvbach91 commented on www/wald03/hw08/main.js
> +    return ((secondFahrenheiht - 32) * 5) / 9;
farenheit

2022-11-14 14:41 UTC, nvbach91 commented on www/wald03/hw08/main.js
> +    const a_percent = (a / b) * 100;
camelcase

2022-11-14 14:41 UTC, nvbach91 commented on www/wald03/hw08/main.js
> +function aroundAbout(a) {
nazvy funkci by mely odpovidat tomu co funkce dela, tady napr. `const calculateCircleArea = (radius) => { ... }`

2022-11-14 14:41 UTC, nvbach91 commented on www/wald03/hw08/main.js
> +    }
chybi navratova hodnota

2022-11-18 12:00 UTC, wallerdav commented
Opraveno.

2022-11-19 16:10 UTC, nvbach91 requested changes

2022-11-19 16:10 UTC, nvbach91 commented on www/wald03/hw08/main.js
>      }
navratova hodnota teto funkce by mel byt boolean, ne console.log("...");

2022-11-24 13:56 UTC, nvbach91 requested changes

2022-11-24 13:56 UTC, nvbach91 commented on www/wald03/hw08/main.js
> +     boolean = true;
`let boolean`

2022-11-24 13:56 UTC, nvbach91 commented on www/wald03/hw08/main.js
> +age = currentYear - ageOfBirth;
`const age`

2022-11-24 14:02 UTC, nvbach91 approved these changes

2022-11-24 14:03 UTC, merged