svoi02-hw08
nvbach91/4IZ268-2022-2023-ZS pull request #32
Opened 2022-11-17 15:39 UTC by eMkoC4

Domácí úkol č. 8, https://esotemp.vse.cz/~svoi02/www/svoi02/hw08/

2022-11-19 16:56 UTC, nvbach91 requested changes

2022-11-19 16:56 UTC, nvbach91 commented on www/svoi02/hw08/homework.js
> +const pepe_age = 42;
tohle ma byt rok narozeni

2022-11-19 16:56 UTC, nvbach91 commented on www/svoi02/hw08/homework.js
> +  multiples = [];
chybi deklarace promenne

2022-11-19 16:56 UTC, nvbach91 commented on www/svoi02/hw08/homework.js
> +  content = (3.14159265 * r ** 2).toFixed(2);
deklarace

2022-11-19 16:56 UTC, nvbach91 commented on www/svoi02/hw08/homework.js
> +  volume = ((1 / 3) * 3.14159265 * r ** 2 * v).toFixed(2);
deklarace

2022-11-25 14:03 UTC, eMkoC4 commented
Fixed in second commit

2022-11-25 17:09 UTC, nvbach91 commented
@eMkoC4 Vas commit neprinesl zadne nove zmeny

2022-12-04 10:21 UTC, eMkoC4 commented
Nevím proč se to nenahrálo předtím, opraveno.

2022-12-09 12:12 UTC, nvbach91 approved these changes

2022-12-09 12:12 UTC, merged