lasj06-hw08
nvbach91/4IZ268-2022-2023-ZS pull request #36
Opened 2022-11-17 21:32 UTC by Gladyon

Odevzdávám domácí úkol č.8 https://esotemp.vse.cz/~lasj06/hw08/

2022-11-17 21:33 UTC, Gladyon commented
Bohužel mi pull request přes main dle návodu nefungoval

2022-11-19 17:14 UTC, nvbach91 requested changes

2022-11-19 17:14 UTC, nvbach91 commented on www/lasj06/hw08/main.js
> +    volume = Math.PI * 1/3 * h * r * r;
`const volume` ?

2022-11-19 17:14 UTC, nvbach91 commented on www/lasj06/hw08/main.js
> +        area = Math.sqrt(s*(s-a)*(s-b)*(s-c))
`const area` ?

2022-11-19 22:46 UTC, Gladyon commented
opraveno

2022-11-24 13:27 UTC, nvbach91 commented
Vzdyt tu stejnou chybu mate i na dalsich mistech v kodu, co takhle projit cely ukol a doplnit to tam?

2022-11-24 17:44 UTC, Gladyon commented
Opraveno

2022-11-25 01:22 UTC, nvbach91 approved these changes

2022-11-25 01:26 UTC, merged