korn03-hw08
nvbach91/4IZ268-2022-2023-ZS pull request #40
Opened 2022-11-18 01:15 UTC by Nikinayzer

DÚ 8 + https://esotemp.vse.cz/~korn03/cv08/

2022-11-19 17:26 UTC, nvbach91 requested changes

2022-11-19 17:26 UTC, nvbach91 commented on www/korn03/hw8/homework.js
> +let teplotaC = 20;
`let temperatureC`

2022-11-19 17:26 UTC, nvbach91 commented on www/korn03/hw8/homework.js
> +function kdoKoho(prvniCislo, druheCislo) {
`compare`

2022-11-19 17:26 UTC, nvbach91 commented on www/korn03/hw8/homework.js
> +function obsahKruznice(polomer) {
`circleArea`

2022-11-19 17:26 UTC, nvbach91 commented on www/korn03/hw8/homework.js
> +    obsah = polomer ** 2 * Math.PI;
`const`?

2022-11-19 17:26 UTC, nvbach91 commented on www/korn03/hw8/homework.js
> +function objemKuzelu(polomer, vyska) {
`calculateConeVolume`

2022-12-02 14:34 UTC, Nikinayzer commented
@nvbach91 opravil jsem Vaše připomínky. Děkují.

2022-12-02 17:37 UTC, nvbach91 approved these changes

2022-12-02 17:37 UTC, merged